sepandhaghighi/clox

CHANGELOG.md
README.md

Version 0.1

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
README.md
SECURITY.md
clox/params.py
otherfiles/version_check.py
setup.py

Version 0.2

---

CHANGELOG.md
README.md
clox/functions.py
clox/params.py

#14 
- `--vertical` argument added

Vertical mode

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
README.md
SECURITY.md
clox/params.py
otherfiles/version_check.py
setup.py

Version 0.3

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
README.md
SECURITY.md
clox/params.py
otherfiles/version_check.py
setup.py

Version 0.4

---

CHANGELOG.md
README.md
clox/functions.py

#21 
- `--hide-date` argument added

`--hide-date`

---

CHANGELOG.md
README.md
clox/functions.py

- `--hide-timezone` argument added

`--hide-timezone`

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
README.md
SECURITY.md
clox/params.py
otherfiles/version_check.py
setup.py

Version 0.5

---

clox/functions.py

- `run_clock` function refactored
- `print_calendar` function refactored
- String templates modified

Minor edits

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
README.md
SECURITY.md
clox/params.py
otherfiles/version_check.py
setup.py

Version 0.6

---

CHANGELOG.md
README.md
clox/functions.py
clox/params.py
dev-requirements.txt
requirements.txt

- `--date-system` argument added
- `README.md` updated

Date System

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
README.md
SECURITY.md
clox/params.py
otherfiles/version_check.py
setup.py

Version 0.7

---

CHANGELOG.md
clox/functions.py
clox/params.py

- Input case sensitivity bug fixed

Case Sensitivity

---

CHANGELOG.md
clox/functions.py
clox/params.py

#46 
- Timezone difference added

Timezone Difference

---

.github/workflows/publish_pypi.yml
.github/workflows/test.yml
CHANGELOG.md
setup.py

- Test system modified
- `Python 3.6` support dropped

`Ubuntu-20.04` --> `Ubuntu-22.04`

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
README.md
SECURITY.md
clox/params.py
otherfiles/version_check.py
setup.py

Version 0.9

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
README.md
SECURITY.md
clox/params.py
otherfiles/version_check.py
setup.py

Version 1.0

---

.github/workflows/test.yml
CHANGELOG.md
clox/functions.py
clox/params.py

#58 
I added the parameter which is passed to the `GregorianCalendar` and `JalaliCalendar`.
I tried to implement it as smooth as possible. So users input the first weekday in numbers `int` and not `str`s. Also the same number means differently in the two calendar as it shown before:
```
$ clox --calendar=year --date-system=jalAli --country=De --first-weekday=0
Today: Thursday, Ordibehesht 18, 1404
Timezone: EUROPE/BERLIN (08h60m ahead)
1404
Farvardin                Ordibehesht                 Khordad
Sa Su Mo Tu We Th Fr      Sa Su Mo Tu We Th Fr      Sa Su Mo Tu We Th Fr
1             1  2  3  4  5                      1  2
2  3  4  5  6  7  8       6  7  8  9 10 11 12       3  4  5  6  7  8  9
9 10 11 12 13 14 15      13 14 15 16 17 18 19      10 11 12 13 14 15 16
16 17 18 19 20 21 22 …
```

`--first-weekday` parameter added

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
README.md
SECURITY.md
clox/params.py
otherfiles/version_check.py
setup.py

Version 1.1

---

.github/workflows/test.yml
CHANGELOG.md
clox/functions.py
clox/params.py

- Local/Timezone offset printing bug fixed
- Test system modified
- `OFFSET_FORMAT` updated

Offset Bug

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
README.md
SECURITY.md
clox/params.py
otherfiles/version_check.py
setup.py

Version 1.2

---

.github/workflows/publish_pypi.yml
CHANGELOG.md
clox/functions.py

- Jupyter notebook support added
- `detect_environment` function added
- `clear_screen` function modified
- `run_clock` function modified

Detect Environment
